[package]
name = "walinux"
version = "0.1.2"
description = "An unofficial, lightweight WhatsApp Web desktop client for Linux"
authors = ["Sullivan <epicrr001@gmail.com>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/salarzeidanlou/WaLinux"
homepage = "https://github.com/salarzeidanlou/WaLinux"
readme = "../README.md"
keywords = ["linux", "desktop", "tauri", "whatsapp"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "walinux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-notification = "2"
tokio = { version = "1", features = ["fs"] }
dirs = "6.0"
infer = "0.3"
open = "5"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"
